// Generated by https://quicktype.io

export interface CervezaData {
    ok:       boolean;
    total:    number;
    cervezas: Cerveza[];
}

export interface Cerveza {
    estado:      boolean;
    precioUnit:  number;
    stock:       number;
    tipoCerveza: TipoCerveza;
    nombre:      string;
    marca:       string;
    id:          string;
}

export interface TipoCerveza {
    _id:    string;
    nombre: string;
}


export interface beerCart{
    id: string;
    cantidad: number;
    precio: number;
    stock: number;
}