// Generated by https://quicktype.io

export interface DataDetalleVenta {
    ok:             boolean;
    total:          number;
    detallesVentas: DetallesVenta[];
}

export interface DetallesVenta {
    estado:   boolean;
    cantidad: number;
    precio:   number;
    cerveza:  Cerveza;
    venta:    string;
    id:       string;
}

export interface Cerveza {
    precioUnit: number;
    _id:        string;
    nombre:     string;
    marca:      string;
}
