// Generated by https://quicktype.io

export interface DataVentasByUser {
    ok:             boolean;
    ventasUsuarios: VentasUsuario[];
}

export interface VentasUsuario {
    estado:      boolean;
    precioTotal: number;
    _id:         string;
    usuario:     Usuario;
    createdAt:   string;
    updatedAt:   string;
    __v:         number;
    detalle:     Detalle[];
}

export interface Detalle {
    estado:   boolean;
    cantidad: number;
    precio:   number;
    cerveza:  string;
    venta:    string;
    id:       string;
}

export interface Usuario {
    _id:      string;
    nombre:   string;
    apellido: string;
}
